aws-samples/aurora-dsql-samples

- .github/workflows/java-pgjdbc-integ-tests.yml
- java/.gitignore
- java/pgjdbc/README.md
- java/pgjdbc/build.gradle.kts
- java/pgjdbc/pom.xml
- java/pgjdbc/settings.gradle.kts
- java/pgjdbc/src/main/java/org/example/Example.java
- java/pgjdbc/src/test/java/org/example/DsqlExampleTest.java
This PR updates the pgJDBC example. It includes the following changes:
- Synchronize the example with the publicly available docs [here](https://docs.aws.amazon.com/aurora-dsql/latest/userguide/SECTION_program-with-pgjdbc.html)
- Clean up and improve the documentation/comments
- Fix dependencies
- Add non-admin connection example
----
> Update pgJDBC example to include non-admin and connection refresh logic

- .github/workflows/python-sqlalchemy-integ-tests.yml
- python/sqlalchemy/README.md
- python/sqlalchemy/requirements.txt
- python/sqlalchemy/setup.sh
- python/sqlalchemy/src/example.py
- python/sqlalchemy/test/test_example.py
*Description of changes:*
Adds non-admin logic and connection token refresh
- Adds a listener for non-admin, and updates the search path to myschema.
- Adds a listener to set a new token every time a connection is created. The connection is created immediately after the parameter is updated.
- Connection refresh can be tested by setting the token expiry to 2 seconds, and then setting a parameter pool_recycle to 1 second in the engine creation. This ensures that it will attempt to open a new connection every second, and that the first token created will not be valid anymore after 1 second. It should succeed, as it created a new token each time it connected. I also tested the negative case, by removing the listener altogether and using a single token with a short timeout, to prove that it …
> Update SQLAlchemy example to include non-admin and connection refresh logic

- .github/workflows/ruby-rubypg-integ-tests.yml
- ruby/ruby-pg/Gemfile
- ruby/ruby-pg/README.md
- ruby/ruby-pg/lib/hello_dsql.rb
- ruby/ruby-pg/spec/smoke_spec.rb
This PR updates the Ruby-pg example.
Description of changes:
- Add non-admin connection example
- Split connection creation logic into a method to address token refresh concerns
- Clean up and improve the documentation/comments
> Update Ruby-pg samples and README.md

- .github/workflows/cpp-libpq-integ-tests.yml
- cpp/libpq/README.md
- cpp/libpq/src/libpq_example.cpp
This PR updates the cpp libpq example
Description of changes:
- Add non-admin connection handing
- Update the documentation in README.md
> Update cpp libpq samples and README.md

- rust/sqlx/src/main.rs
**This PR was originally opened by Marc Bowes as #111, but I managed to mess up the state of that PR while trying to remove the `Cargo.toml` change. Here is a replacement which only changes the `main.rs` file.**
Launch a tokio task that updates the password every 10 minutes. The tokens expire every 15 minutes. This is a stopgap until sqlx can be made to support this natively.
See also: https://github.com/launchbadge/sqlx/issues/445
> rust/sqlx: Refresh the token every 10 minutes

- javascript/postgres-js/.gitignore
- javascript/postgres-js/README.md
- javascript/postgres-js/package.json
- javascript/postgres-js/src/index.js
- javascript/postgres-js/test/smoke.test.js
- Adds PostgresJS sample
Thank you for your contribution!
> Add Postgres.js sample with token refresh and non-admin

- python/psycopg/README.md
- python/psycopg2/README.md
- python/sqlalchemy/README.md
- ruby/rails/petclinic/README.md
- ruby/ruby-pg/README.md
Fix documentation and remove references to other certificates than `AmazonRootCA1.pem`.
> Remove references to invalid CAs

- README.md
Changes in root `README.md`:
* Sort items alphabetically by language;
* Use `JavaScript` instead of `Javascript`;
* Add missing reference to golang cluster management page.
> Fix root README

- java/cluster_management/pom.xml
- java/cluster_management/src/main/java/org/example/CreateMultiRegionClusters.java
- java/cluster_management/src/main/java/org/example/DeleteMultiRegionClusters.java
- java/cluster_management/src/test/java/org/example/DsqlClusterManagementTest.java
What it says on the tin. I also removed the `ListTagsForResource` call in the sweeper because the latest SDK has `Tags` on the `GetClusterResponse` (hooray!)
---
Thank you for your contribution!
> java: Add multi-Region examples for cluster management

- .github/workflows/javascript-postgresjs-integ-tests.yml
- Adds an integration test workflow for Postgres-js
Thank you for your contribution!
> Add Postgres-js CI

- .github/scripts/clean-clusters.sh
- .github/workflows/clean-clusters.yml
- .github/workflows/cpp-cm-integ-tests.yml
- .github/workflows/dotnet-cm-integ-tests.yml
- .github/workflows/go-cm-integ-tests.yml
- .github/workflows/java-cm-integ-tests.yml
- .github/workflows/javascript-cm-integ-tests.yml
- .github/workflows/python-cm-integ-tests.yml
- .github/workflows/ruby-cm-integ-tests.yml
- .github/workflows/rust-cm-integ-tests.yml
- java/cluster_management/src/test/java/org/example/DsqlClusterManagementTest.java
- python/cluster_management/test/test_dsql_cluster_management.py
This PR fixes #136 
This change introduces a script to clean up lingering clusters. It only applies to clusters that are not already deleting, and which have the correct `Repo` tag. The script also exits early if the `IS_CI` flag isn't set for additional safety.
The `clean-clusters.yml` workflow can be called to clean up the clusters generated by other workflows.o
Things needed before review:
> Clean up lingering clusters after test runs

- go/cluster_management/cmd/create_multi_region/create_multi_region.go
- go/cluster_management/cmd/create_single_region/create_single_region.go
- go/pgx/example.go
They're already set by `config.WithRegion`
---
Thank you for your contribution!
> go: Remove unnecessary region options

- .github/workflows/cpp-cm-integ-tests.yml
- .github/workflows/dotnet-cm-integ-tests.yml
- .github/workflows/go-cm-integ-tests.yml
- .github/workflows/java-cm-integ-tests.yml
- .github/workflows/javascript-cm-integ-tests.yml
- .github/workflows/python-cm-integ-tests.yml
- .github/workflows/ruby-cm-integ-tests.yml
- .github/workflows/rust-cm-integ-tests.yml
This PR modifies the cluster management workflows to ensure only 1 job runs at any given time against each account. This will help prevent conflicts where the cluster cleanup job deletes clusters that are being used by a testing job.
I could have put the `concurrency` limit on the workflow, which would ensure all jobs and cleanup steps finish before any other workflow can begin. I chose to put it on the `job` here instead, so that other tasks like formatting checks can complete and provide quick feedback in the PR without having to potentially wait for other workflows to finish.
I tested this change by running 2 of the same workflow, and we can see here the job is waiting before proceeding since there is already a job running. We can also see the formatting check was not blocked.
There is …
> Limit cluster management job concurrency

- .github/workflows/go-cm-integ-tests.yml
- .github/workflows/go-pgx-integ-tests.yml
This PR moves the `GOPROXY=direct` definition to a higher level in the workflows, to ensure it applies to the entire setup process.
While testing the action locally I noticed several of the setup steps were having trouble with blocked proxy calls. This was happening before we got to the `GOPROXY` definition, which indicated there were actions which weren't covered by the variable definition.
> Move GOPROXY definition to top level of workflows

- .github/workflows/cpp-cm-integ-tests.yml
- .github/workflows/dotnet-cm-integ-tests.yml
- .github/workflows/go-cm-integ-tests.yml
- .github/workflows/java-cm-integ-tests.yml
- .github/workflows/javascript-cm-integ-tests.yml
- .github/workflows/python-cm-integ-tests.yml
- .github/workflows/ruby-cm-integ-tests.yml
- .github/workflows/rust-cm-integ-tests.yml
This PR ensures we run all affected workflows if the `.github/workflows/clean-clusters.yml` file changes.
This should have been included in #144 but I missed it there.
> Trigger workflows on changes to clean-clusters.yml

- .github/workflows/cpp-cm-integ-tests.yml
- .github/workflows/cpp-libpq-integ-tests.yml
This PR updates the C++ workflows to improve the runtime.
The following changes are included:
- Run the build in parallel given the number of processors allocated to the worker
- Disable tests in third-party dependencies
This improves the time it takes to install the AWS SDK from ~8:30 to ~3 minutes.
These changes will have less of an effect on the cluster management tests since the test run there takes a significant amount of time by itself. It will have more of an effect on the `libpq` tests since the test runtime for those is near instant.
> cpp: Run cpp workflows faster

- .github/workflows/cpp-libpq-integ-tests.yml
- cpp/libpq/README.md
- cpp/libpq/src/libpq_example.cpp
This PR configures the `libpq` sample to use `verify-full` instead of `require` for a more secure TLS connection.
In order to configure the trusted certificate, we must download it as part of the build. This aligns the `libpq` sample with other samples which download and verify the server certificate.
> cpp: Use verify-full for libpq sample

- java/pgjdbc/README.md
- java/pgjdbc/src/main/java/org/example/Example.java
This PR modifies the `pgJDBC` example to set `sslNegotiation=direct` as per #150.
I added a section to the `README.md` file which describes more about the TLS configuration, and calls out that direct TLS connections are a new feature and may not be supported by all driver versions. My intention is to add the same section to the `README.md` files of other drivers as they are updated.
> java: Use direct TLS connections for pgJDBC

- dotnet/npgsql/Example.cs
This PR improves a small thing I noticed in the Npgsql sample while modifying it for another purpose.
We previously had `using var` to clean up resources at the end of the method, but since the method is `async`, we can use `await using var` in several places for instances which implement `IAsyncDisposable`. Using the `IAsyncDisposable` variant is better in the context of this method since it is `async`.
> dotnet: Use 'await using' where possible

- go/pgx/README.md
- go/pgx/example.go
- go/pgx/go.mod
- go/pgx/go.sum
This PR modifies the `pgx` example to set `sslnegotiation=direct` as per #150.
As part of this change I had to update the driver version to the latest, since the support for this was added very recently.
I added a section to the `README.md` file which describes more about the TLS configuration, and calls out that direct TLS connections are a new feature and may not be supported by all driver versions. My intention is to add the same section to the `README.md` files of other drivers as they are updated.
> go: Use direct TLS connections for pgx

- .github/workflows/cpp-cm-integ-tests.yml
- .github/workflows/go-cm-integ-tests.yml
- .github/workflows/java-cm-integ-tests.yml
- .github/workflows/javascript-cm-integ-tests.yml
- .github/workflows/python-cm-integ-tests.yml
- .github/workflows/ruby-cm-integ-tests.yml
- .github/workflows/rust-cm-integ-tests.yml
This PR is a cosmetic change to the structure of the cluster management `.yml` files.
The concurrency blocks were added in #149, but while working on #162 I noticed they should really be grouped with the job configuration at the top. This was done inconsistently in #149 for some reason, with the .NET sample already grouping it at the top of the job configuration.
Having the `concurrency` block at the top makes it a bit easier to spot given the steps for the job are variable length and sometimes quite complex.
> Configure cluster management concurrency in a consistent place

- .github/workflows/cpp-libpq-integ-tests.yml
- .github/workflows/dotnet-npgsql-integ-tests.yml
- .github/workflows/go-pgx-integ-tests.yml
- .github/workflows/java-pgjdbc-integ-tests.yml
- .github/workflows/javascript-node-postgres-integ-tests.yml
- .github/workflows/javascript-postgresjs-integ-tests.yml
- .github/workflows/python-psycopg2-integ-tests.yml
- .github/workflows/python-psycopg3-integ-tests.yml
- .github/workflows/python-sqlalchemy-integ-tests.yml
- .github/workflows/ruby-rubypg-integ-tests.yml
- .github/workflows/rust-sqlx-integ-test.yml
- .github/workflows/typescript-sequelize-integ-tests.yml
- .github/workflows/typescript-type-orm-integ-tests.yml
This PR updates the workflow definitions for the various drivers to ensure only 1 job runs at a time for each workflow.
Since the workflows use a statically configured cluster, any attempts to run 2 jobs against the same cluster at the same time may result in conflicts and failed jobs. By configuring the `concurrency` property we can instruct jobs to wait until previous jobs for the same workflow are complete.
Related: #149 
> Limit sample concurrency to prevent cluster usage conflicts

- cpp/libpq/README.md
- cpp/libpq/src/libpq_example.cpp
This PR modifies the `libpq` example to set `sslnegotiation=direct` as per #150.
I added a section to the `README.md` file which describes more about the TLS configuration, and calls out that direct TLS connections are a new feature and may not be supported by all driver versions. My intention is to add the same section to the `README.md` files of other drivers as they are updated.
> cpp: Use direct TLS connections for libpq

- ruby/ruby-pg/README.md
- ruby/ruby-pg/lib/hello_dsql.rb
This PR modifies the `ruby-pg` sample to set `sslnegotiation=direct` as per #150.
It does this conditionally based on the underlying `libpq` version, since the same `ruby-pg` version can be used with multiple versions of `libpq`. I verified in the release notes [here](https://www.postgresql.org/docs/release/17.0/) that `sslnegotiation` has been available since the `17.0` release and was not added as a minor version bump.
I added a section to the `README.md` file which describes more about the TLS configuration, and calls out that direct TLS connections are a new feature and may not be supported by all driver versions. This section was already reviewed in #160, and will be added to all samples which support direct TLS connections.
By submitting this pull request, I confirm that my …
> ruby: Use direct TLS connections for ruby-pg

- python/sqlalchemy/README.md
- python/sqlalchemy/src/example.py
This PR modifies the `SQLAlchemy` sample to set `sslnegotiation=direct` as per #150.
It does this conditionally based on the underlying `libpq` version, since the same `psycopg2` version can be used with multiple versions of `libpq`. I verified in the release notes [here](https://www.postgresql.org/docs/release/17.0/) that `sslnegotiation` has been available since the `17.0` release and was not added as a minor version bump.
As with #167, at the time of writing, the `psycopg2-binary` package includes `libpq` 16.0, which doesn't support the `sslnegotiation` parameter. See the other PR for more detail, as the same applies here given SQLAlchemy's use of `psycopg2` in this sample.
I added a section to the `README.md` file which describes more about the TLS configuration, and calls out that …
> python: Use direct TLS connections for SQLAlchemy

- python/psycopg2/README.md
- python/psycopg2/src/example.py
This PR modifies the `psycopg2` sample to set `sslnegotiation=direct` as per #150.
It does this conditionally based on the underlying `libpq` version, since the same `psycopg2` version can be used with multiple versions of `libpq`. I verified in the release notes [here](https://www.postgresql.org/docs/release/17.0/) that `sslnegotiation` has been available since the `17.0` release and was not added as a minor version bump.
At the time of writing, the `psycopg2-binary` package includes `libpq` 16.0, which doesn't support the `sslnegotiation` parameter. I manually checked a version of `psycopg2` compiled against `libpq` 17.4 and the direct TLS connection worked properly. I have kept the sample dependency on the pre-built binary, as it's more approachable in terms of the system requirement …
> python: Use direct TLS connections for psycopg2

- dotnet/npgsql/Example.cs
- dotnet/npgsql/README.md
- dotnet/npgsql/example.csproj
This PR modifies the `Npgsql` sample to set `SslNegotiation = SslNegotiation.Direct` as per #150.
Part of this change is removing support for `netstandard2.0`. We previously provided this for compatibility reasons, but `Npgsql` 9.0.3+ does not support `netstandard2.0` so we can't support .NET Framework while also using `SslNegotiation`. After offline discussion, it was decided we would prioritize the more secure/performant connection type, and those that need `netstandard2.0` can always use an older Npgsql version with the traditional PostgreSQL connection preamble.
I added a section to the `README.md` file which describes more about the TLS configuration, and calls out that direct TLS connections are a new feature and may not be supported by all driver versions. This section was already …
> dotnet: Use direct TLS connections for Npgsql

- .github/workflows/cpp-cm-integ-tests.yml
- .github/workflows/cpp-libpq-integ-tests.yml
- .github/workflows/dotnet-cm-integ-tests.yml
- .github/workflows/go-cm-integ-tests.yml
- .github/workflows/go-pgx-integ-tests.yml
- .github/workflows/java-cm-integ-tests.yml
- .github/workflows/java-pgjdbc-integ-tests.yml
- .github/workflows/javascript-cm-integ-tests.yml
- .github/workflows/javascript-node-postgres-integ-tests.yml
- .github/workflows/javascript-postgresjs-integ-tests.yml
- .github/workflows/python-cm-integ-tests.yml
- .github/workflows/python-sqlalchemy-integ-tests.yml
- .github/workflows/ruby-pg-integ-tests.yml
- .github/workflows/ruby-rubypg-integ-tests.yml
- .github/workflows/rust-cm-integ-tests.yml
- .github/workflows/rust-sqlx-integ-test.yml
- .github/workflows/typescript-sequelize-integ-tests.yml
- .github/workflows/typescript-type-orm-integ-tests.yml
Standardize GitHub Actions names.
> Standardize GitHub actions names

- .github/workflows/go-pgx-integ-tests.yml
- go/pgx/README.md
- go/pgx/example.go
- go/pgx/example_test.go
This PR modifies the Go pgx driver sample to resolve a race-condition with the way the pool was being handled.
The pgx pool was previously wrapped in a custom construct which replaced the inner pool when the token needed to be refreshed. This had a few issues:
- Established connections do not need to be replaced until the `MaxConnLifetime` expires, even if the token which was used to authenticate them has already expired.
- The token refresh logic replaced the pool, which meant any parties with a reference to the old pool would experience errors after the pool was closed.
- A mutex was used to reconfigure the pool wrapper, which means any safe access to perform operations on the pool should also acquire the mutex. This mutex acquisition was missing in the sample, and this approach also …
> pgx: Configure connections using hooks rather than replacing pool

- .github/workflows/javascript-cm-integ-tests.yml
- .github/workflows/javascript-node-postgres-integ-tests.yml
- .github/workflows/javascript-postgresjs-integ-tests.yml
- .github/workflows/lambda-nodejs-integ-tests.yml
- .github/workflows/typescript-sequelize-integ-tests.yml
- .github/workflows/typescript-type-orm-integ-tests.yml
- javascript/node-postgres/package-lock.json
- javascript/postgres-js/package-lock.json
- lambda/.gitignore
- typescript/sequelize/.gitignore
- typescript/sequelize/package-lock.json
This PR ensures the dependencies described by the Node.js packages in the repo will use the same dependencies across all developer machines, including the workflows.
The change adds `package-lock.json` files where they were previously missing, and swaps the workflow files to use `npm ci` to avoid dependency versions being changed on the fly. In at least one case the `npm ci` failed when testing locally since the `package.json` and `package-lock.json` files were out of sync which should never happen on `main`.
> Use package-lock.json and npm ci for predictable dependencies
